# 矩阵运算

## 数乘运算

In [1]:
import numpy as np
A = np.arange(10).reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
2*A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [16]:
1 + A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
A - 1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [3]:
B = np.random.randint(0, 10, size=(2, 5))
B

array([[4, 8, 3, 5, 7],
       [9, 6, 6, 6, 6]])

In [18]:
A + B

array([[ 4,  9,  5,  8, 11],
       [14, 12, 13, 14, 15]])

In [19]:
A - B

array([[-4, -7, -1, -2, -3],
       [-4,  0,  1,  2,  3]])

In [10]:
C = np.arange(15).reshape(5, 3)
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
A.dot(C)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [20]:
A*B

array([[ 0,  8,  6, 15, 28],
       [45, 36, 42, 48, 54]])

In [21]:
A.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [22]:
C.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

## 聚合操作

In [25]:
D = np.random.random(10)
D

array([ 0.70908471,  0.29268356,  0.69885019,  0.28796429,  0.04189265,
        0.36932107,  0.0641322 ,  0.63989077,  0.02753356,  0.0605743 ])

In [26]:
np.sum(D)

3.1919272951030706

In [27]:
np.min(D)

0.027533561561906672

In [28]:
np.max(D)

0.70908470606410545

In [29]:
np.mean(D)

0.31919272951030708

In [30]:
np.std(D)

0.26402525382852743

In [31]:
X = np.arange(6).reshape(2, 3)
X

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
np.sum(X)

15

In [33]:
np.sum(X, axis=1)

array([ 3, 12])

In [34]:
np.prod(X)

0

In [35]:
np.prod(X + 1)

720

In [36]:
np.mean(X)

2.5

In [37]:
np.median(X)

2.5

In [38]:
np.var(X)

2.9166666666666665

In [39]:
np.std(X)

1.707825127659933

In [41]:
X

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
np.min(X)

0

In [43]:
np.argmin(X)

0

In [50]:
x = np.random.random(10)
x

array([ 0.17035458,  0.8968506 ,  0.01007584,  0.45925501,  0.6838149 ,
        0.32393039,  0.53746647,  0.68561243,  0.66195346,  0.32696068])

In [51]:
np.min(x)

0.010075835471876626

In [52]:
np.argmin(x)

2

In [53]:
np.sort(x)

array([ 0.01007584,  0.17035458,  0.32393039,  0.32696068,  0.45925501,
        0.53746647,  0.66195346,  0.6838149 ,  0.68561243,  0.8968506 ])

In [54]:
np.argsort(x)

array([2, 0, 5, 9, 3, 6, 8, 4, 7, 1])

In [55]:
X

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
np.random.shuffle(X)

In [59]:
X

array([[3, 4, 5],
       [0, 1, 2]])

In [60]:
np.random.shuffle(X)

In [61]:
X

array([[3, 4, 5],
       [0, 1, 2]])

In [75]:
X1 = np.random.randint(0, 15, size=(3, 5))
X1

array([[ 8,  1,  8, 12,  4],
       [ 8,  6,  6,  6, 13],
       [13,  2,  5, 11,  4]])

In [76]:
np.sort(X1)

array([[ 1,  4,  8,  8, 12],
       [ 6,  6,  6,  8, 13],
       [ 2,  4,  5, 11, 13]])

In [77]:
np.argsort(X1)

array([[1, 4, 0, 2, 3],
       [1, 2, 3, 0, 4],
       [1, 4, 2, 3, 0]])