In [1]:
import numpy as np

raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [2]:
XTrain = np.array(raw_data_X)
yTrain = np.array(raw_data_y)

In [3]:
XTrain

array([[ 3.39353321,  2.33127338],
       [ 3.11007348,  1.78153964],
       [ 1.34380883,  3.36836095],
       [ 3.58229404,  4.67917911],
       [ 2.28036244,  2.86699026],
       [ 7.42343694,  4.69652288],
       [ 5.745052  ,  3.5339898 ],
       [ 9.17216862,  2.51110105],
       [ 7.79278348,  3.42408894],
       [ 7.93982082,  0.79163723]])

In [4]:
yTrain

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [5]:
x = np.array([8.093607318, 3.365731514])

In [6]:
%run ../pycharm/kNN.py

In [7]:
predicty = kNNClassify(6, XTrain, yTrain, x)

In [8]:
predicty

1

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
kNNClassifier = KNeighborsClassifier(n_neighbors=6)

In [11]:
kNNClassifier.fit(XTrain, yTrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [13]:
kNNClassifier.predict(x.reshape(1, -1))

array([1])