In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

## train test split

### 先乱序

In [3]:
# permutation(10)，表示返回一个乱序的一维向量，元素从0到10
shuffleIndexs = np.random.permutation(len(X))
shuffleIndexs

array([ 30,  15,  84,   5, 124,  49,  38,  44,  89, 102,  13, 103,  67,
        61,  41,  82,  66,  98,  69,   9,  31,  43,  20,  29,  88,  19,
       137, 127, 101,  18, 111,  76, 139,   3, 132, 133,  34, 105,  94,
        51, 130,  45,  99, 116, 126,  72,   8,  59,  21,  52,  62,  27,
       117, 149,  36,  47,   7,  79,  73, 136,  65,  25,  26,   6, 142,
       109, 131, 104,  96,  60,  75,  39, 145,  80, 121,   1,  93,  10,
        14,  48,   2, 129,  57,  42, 120, 112,  24, 118,   0,  35, 123,
         4, 110,  85,  32, 115,  90,  55, 138, 134,  12,  87, 114,  56,
        91,  28, 148,  46,  78,  86,  53,  64,  50,  58,  37,  16, 106,
       128,  54,  74,  77,  23, 141, 122,  68,  33,  81,  63,  97, 119,
       144,  70, 113,  95,  71,  92, 125, 108, 107,  83, 135, 147, 146,
       140,  22,  11, 143, 100,  40,  17])

In [4]:
testRatio = 0.2
testSize = int(len(X) * testRatio)
testSize

30

In [5]:
testIndexs = shuffleIndexs[:testSize]
trainIndexs = shuffleIndexs[testSize:]

In [6]:
XTrain = X[trainIndexs]
yTrain = y[trainIndexs]
print(XTrain.shape)
print(yTrain.shape)

(120, 4)
(120,)


In [7]:
XTest = X[testIndexs]
yTest = y[testIndexs]
print(XTest.shape)
print(yTest.shape)

(30, 4)
(30,)


## 使用我们的训练/测试数据分割算法

In [8]:
from myML.modelSelection import train_test_split

In [9]:
X_train, y_train, X_test, y_test = train_test_split(X, y)

In [10]:
X_train.shape

(120, 4)

In [11]:
y_train.shape

(120,)

In [12]:
X_test.shape

(30, 4)

In [13]:
y_test.shape

(30,)

In [14]:
from myML.kNN import KNNClassifier

In [15]:
my_knn_classifier = KNNClassifier(6)

In [16]:
my_knn_classifier.fit(X_train, y_train)

kNN(k=6)

In [17]:
my_y_test = my_knn_classifier.predict(X_test)

In [18]:
my_y_test

array([2, 2, 1, 2, 0, 1, 1, 2, 1, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 1, 2, 0, 1,
       1, 2, 2, 2, 0, 0, 1])

In [19]:
y_test

array([2, 1, 1, 2, 0, 2, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 1, 2, 0, 1,
       1, 2, 2, 2, 0, 0, 1])

In [20]:
sum(my_y_test == y_test)

27

In [21]:
sum(my_y_test == y_test) / len(y_test)

0.90000000000000002

In [22]:
my_knn_classifier.fit(X_train, y_train)

kNN(k=6)

In [23]:
my_knn_classifier.accuracy_score(X_test, y_test)

0.90000000000000002