In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

## train test split

### 先乱序

In [3]:
# permutation(10)，表示返回一个乱序的一维向量，元素从0到10
shuffleIndexs = np.random.permutation(len(X))
shuffleIndexs

array([ 16,   7, 107,  93,  90,   6, 138,  89,   0, 144, 132,  87, 116,
       148,  59,  69, 139,  13,  38, 136, 135,  20,  51,  91,  47,  17,
        39,  27,  82,  55,  67, 114,  83,  43, 118, 140,  29,  81,  79,
        35,  95, 127, 137,   1,  61,  32,  24,  72, 113,   5, 124,  71,
       134,  36, 141,  75, 120, 128,   9, 100,  10,  94,  42,  28,  80,
        12, 145,  64,  76, 103,  66,  97, 101,  68,  53,  41, 117,  63,
        14, 130, 129, 109,  26,  88, 104,  86,  44,  99,  34,  65, 142,
       131,  57, 105, 119,  84, 102, 149,  22,  18,  31, 126,   4,  21,
       143, 122,  62,  50,  98,  15,  40,  56,  25, 125,  52,  23, 106,
        60,  49,  70, 108,  11,  77,   8, 112,  19, 123,   2, 133,  46,
        96,  33, 115, 146,  54,  92,  30,  37,  45,  78,  58,   3, 147,
       121,  48,  73,  74, 111,  85, 110])

In [4]:
testRatio = 0.2
testSize = int(len(X) * testRatio)
testSize

30

In [5]:
testIndexs = shuffleIndexs[:testSize]
trainIndexs = shuffleIndexs[testSize:]

In [6]:
XTrain = X[trainIndexs]
yTrain = y[trainIndexs]
print(XTrain.shape)
print(yTrain.shape)

(120, 4)
(120,)


In [7]:
XTest = X[testIndexs]
yTest = y[testIndexs]
print(XTest.shape)
print(yTest.shape)

(30, 4)
(30,)


## 使用我们的训练/测试数据分割算法

In [8]:
from myML.modelSelection import train_test_split

In [9]:
X_train, y_train, X_test, y_test = train_test_split(X, y)

In [10]:
X_train.shape

(120, 4)

In [11]:
y_train.shape

(120,)

In [12]:
X_test.shape

(30, 4)

In [13]:
y_test.shape

(30,)

In [14]:
from myML.kNN import KNNClassifier

In [15]:
my_knn_classifier = KNNClassifier(6)

In [16]:
my_knn_classifier.fit(X_train, y_train)

kNN(k=6)

In [17]:
my_y_test = my_knn_classifier.predict(X_test)

In [18]:
my_y_test

array([1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 2, 2, 1, 1, 1,
       1, 0, 1, 2, 1, 1, 2])

In [19]:
y_test

array([1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 2, 2, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 2])

In [20]:
sum(my_y_test == y_test)

29

In [22]:
sum(my_y_test == y_test) / len(y_test)

0.96666666666666667