In [6]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [7]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

## train test split

### 先乱序

In [10]:
# permutation(10)，表示返回一个乱序的一维向量，元素从0到10
shuffleIndexs = np.random.permutation(len(X))
shuffleIndexs

array([ 10,  87,  84,  58,  81,  91,  12,   6,  28,  62, 109, 107,  31,
       126, 105,  98,  24, 111,  76, 140, 139,  42,  55,  89,  46,  64,
         4,  86,  30, 149, 102,  20, 116,  47, 120,  45,  44, 101,  57,
       112,  14,  49, 128, 106,  33,  97,  21,  17,  85,  93, 113, 127,
         0,  60,  50,  73,  26, 142,  25, 130,  90,  96, 135, 129,  69,
        38,  65,  75,  11,  67,  61, 103,  92, 125, 131,  40,   9,  16,
       147,  77, 110,  99,   1, 145,  22,  78, 134, 123, 118,  39,  27,
        34,  54,  43, 124, 144,   3, 132,   2, 100,  83, 141,  94,  88,
        74,  13, 121,  18,  79, 143,  59,  82, 108,  19,  71,  66,  41,
        29,  68,  37,  53,  95,  23, 115, 119,  63, 133,  51,  48,  80,
        35,  52,  15, 114,  70, 117,  72,  32, 148, 138, 146,   5, 136,
        36,   8, 122, 104,  56, 137,   7])

In [9]:
testRatio = 0.2
testSize = int(len(X) * testRatio)
testSize

30

In [11]:
testIndexs = shuffleIndexs[:testSize]
trainIndexs = shuffleIndexs[testSize:]

In [12]:
XTrain = X[trainIndexs]
yTrain = y[trainIndexs]
print(XTrain.shape)
print(yTrain.shape)

(120, 4)
(120,)


In [13]:
XTest = X[testIndexs]
yTest = y[testIndexs]
print(XTest.shape)
print(yTest.shape)

(30, 4)
(30,)


## 使用我们的训练/测试数据分割算法

In [3]:
from pycharm.myML.modelSelection import train_test_split

In [8]:
X_train, y_train, X_test, y_test = train_test_split(X, y)

In [10]:
X_train.shape

(120, 4)

In [11]:
y_train.shape

(120,)

In [12]:
X_test.shape

(30, 4)

In [13]:
y_test.shape

(30,)

In [14]:
from pycharm.myML.kNN import KNNClassifier

In [15]:
my_knn_classifier = KNNClassifier(6)

In [16]:
my_knn_classifier.fit(X_train, y_train)

kNN(k=6)

In [18]:
my_y_test = my_knn_classifier.predict(X_test)

In [19]:
my_y_test

array([0, 2, 2, 2, 2, 0, 1, 2, 1, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0,
       2, 0, 1, 1, 2, 0, 0])

In [20]:
y_test

array([0, 2, 2, 2, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0,
       2, 0, 1, 2, 2, 0, 0])

In [21]:
sum(my_y_test == y_test)

28

In [22]:
sum(my_y_test == y_test) / len(y_test)

0.93333333333333335